modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${name}"
logoFile = "assets/rubinated_nether/icon.png"
authors = "Artienia, Juniper, Darksonic300"
description = '''
${description}
'''
#logoFile = ""
# Ignore the errors here it's just due to the expand thingy
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
